# JVM Properties
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
java_version=25
## Environment Properties
minecraft_version_range=[26.1,26.2)
neo_version_range=[26,)
loader_version_range=[4,)
modrinth_id=
curseforge_id=
upload=false
publish=true
## Mod Properties
mod_id=bonded_peaks
mod_name=Bonded Peaks
mod_license=LGPL-3.0
mod_version=0.0.1
maven_group=dev.dubhe.bonded
mod_authors=Gugle
mod_description=Sworn by the mountains and rivers, bonded as one team.
